# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smart_can_msgs/AUTONOMOUS_BrakePedalControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AUTONOMOUS_BrakePedalControl(genpy.Message):
  _md5sum = "abb8668963ba2b5c76295810f98dea37"
  _type = "smart_can_msgs/AUTONOMOUS_BrakePedalControl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 AUTONOMOUS_BrakeMotor_Voltage
uint8 AUTONOMOUS_BrakePedalMotor_PER
uint16 AUTONOMOUS_BrakePedalMotor_ACC
uint8 AUTONOMOUS_BrakePedalMotor_EN"""
  __slots__ = ['AUTONOMOUS_BrakeMotor_Voltage','AUTONOMOUS_BrakePedalMotor_PER','AUTONOMOUS_BrakePedalMotor_ACC','AUTONOMOUS_BrakePedalMotor_EN']
  _slot_types = ['uint8','uint8','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       AUTONOMOUS_BrakeMotor_Voltage,AUTONOMOUS_BrakePedalMotor_PER,AUTONOMOUS_BrakePedalMotor_ACC,AUTONOMOUS_BrakePedalMotor_EN

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AUTONOMOUS_BrakePedalControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.AUTONOMOUS_BrakeMotor_Voltage is None:
        self.AUTONOMOUS_BrakeMotor_Voltage = 0
      if self.AUTONOMOUS_BrakePedalMotor_PER is None:
        self.AUTONOMOUS_BrakePedalMotor_PER = 0
      if self.AUTONOMOUS_BrakePedalMotor_ACC is None:
        self.AUTONOMOUS_BrakePedalMotor_ACC = 0
      if self.AUTONOMOUS_BrakePedalMotor_EN is None:
        self.AUTONOMOUS_BrakePedalMotor_EN = 0
    else:
      self.AUTONOMOUS_BrakeMotor_Voltage = 0
      self.AUTONOMOUS_BrakePedalMotor_PER = 0
      self.AUTONOMOUS_BrakePedalMotor_ACC = 0
      self.AUTONOMOUS_BrakePedalMotor_EN = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2BHB().pack(_x.AUTONOMOUS_BrakeMotor_Voltage, _x.AUTONOMOUS_BrakePedalMotor_PER, _x.AUTONOMOUS_BrakePedalMotor_ACC, _x.AUTONOMOUS_BrakePedalMotor_EN))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.AUTONOMOUS_BrakeMotor_Voltage, _x.AUTONOMOUS_BrakePedalMotor_PER, _x.AUTONOMOUS_BrakePedalMotor_ACC, _x.AUTONOMOUS_BrakePedalMotor_EN,) = _get_struct_2BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2BHB().pack(_x.AUTONOMOUS_BrakeMotor_Voltage, _x.AUTONOMOUS_BrakePedalMotor_PER, _x.AUTONOMOUS_BrakePedalMotor_ACC, _x.AUTONOMOUS_BrakePedalMotor_EN))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.AUTONOMOUS_BrakeMotor_Voltage, _x.AUTONOMOUS_BrakePedalMotor_PER, _x.AUTONOMOUS_BrakePedalMotor_ACC, _x.AUTONOMOUS_BrakePedalMotor_EN,) = _get_struct_2BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BHB = None
def _get_struct_2BHB():
    global _struct_2BHB
    if _struct_2BHB is None:
        _struct_2BHB = struct.Struct("<2BHB")
    return _struct_2BHB
