# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smart_can_msgs/kinematic_messages.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class kinematic_messages(genpy.Message):
  _md5sum = "7bc7418ecb7fee03d277ee78209c3d4d"
  _type = "smart_can_msgs/kinematic_messages"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 joint_type
float32 angle
float32 angle_y
float32 angular_velocity
float32 link_length
"""
  __slots__ = ['joint_type','angle','angle_y','angular_velocity','link_length']
  _slot_types = ['uint8','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint_type,angle,angle_y,angular_velocity,link_length

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(kinematic_messages, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joint_type is None:
        self.joint_type = 0
      if self.angle is None:
        self.angle = 0.
      if self.angle_y is None:
        self.angle_y = 0.
      if self.angular_velocity is None:
        self.angular_velocity = 0.
      if self.link_length is None:
        self.link_length = 0.
    else:
      self.joint_type = 0
      self.angle = 0.
      self.angle_y = 0.
      self.angular_velocity = 0.
      self.link_length = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4f().pack(_x.joint_type, _x.angle, _x.angle_y, _x.angular_velocity, _x.link_length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.joint_type, _x.angle, _x.angle_y, _x.angular_velocity, _x.link_length,) = _get_struct_B4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4f().pack(_x.joint_type, _x.angle, _x.angle_y, _x.angular_velocity, _x.link_length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.joint_type, _x.angle, _x.angle_y, _x.angular_velocity, _x.link_length,) = _get_struct_B4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4f = None
def _get_struct_B4f():
    global _struct_B4f
    if _struct_B4f is None:
        _struct_B4f = struct.Struct("<B4f")
    return _struct_B4f
