# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smart_can_msgs/snd_RCUnit_SteeringData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class snd_RCUnit_SteeringData(genpy.Message):
  _md5sum = "dbaee7c633defae17cb1a658b42efed0"
  _type = "smart_can_msgs/snd_RCUnit_SteeringData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 RC_Steering_RightLimit
uint8 RC_Steering_LeftLimit
uint16 RC_SteeringPWM
uint8 RC_SteeringDirection"""
  __slots__ = ['RC_Steering_RightLimit','RC_Steering_LeftLimit','RC_SteeringPWM','RC_SteeringDirection']
  _slot_types = ['uint8','uint8','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       RC_Steering_RightLimit,RC_Steering_LeftLimit,RC_SteeringPWM,RC_SteeringDirection

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(snd_RCUnit_SteeringData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.RC_Steering_RightLimit is None:
        self.RC_Steering_RightLimit = 0
      if self.RC_Steering_LeftLimit is None:
        self.RC_Steering_LeftLimit = 0
      if self.RC_SteeringPWM is None:
        self.RC_SteeringPWM = 0
      if self.RC_SteeringDirection is None:
        self.RC_SteeringDirection = 0
    else:
      self.RC_Steering_RightLimit = 0
      self.RC_Steering_LeftLimit = 0
      self.RC_SteeringPWM = 0
      self.RC_SteeringDirection = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2BHB().pack(_x.RC_Steering_RightLimit, _x.RC_Steering_LeftLimit, _x.RC_SteeringPWM, _x.RC_SteeringDirection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.RC_Steering_RightLimit, _x.RC_Steering_LeftLimit, _x.RC_SteeringPWM, _x.RC_SteeringDirection,) = _get_struct_2BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2BHB().pack(_x.RC_Steering_RightLimit, _x.RC_Steering_LeftLimit, _x.RC_SteeringPWM, _x.RC_SteeringDirection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.RC_Steering_RightLimit, _x.RC_Steering_LeftLimit, _x.RC_SteeringPWM, _x.RC_SteeringDirection,) = _get_struct_2BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BHB = None
def _get_struct_2BHB():
    global _struct_2BHB
    if _struct_2BHB is None:
        _struct_2BHB = struct.Struct("<2BHB")
    return _struct_2BHB
