// Generated by gencpp from file ignition_telemetry_with/AutonomousHeardBit.msg
// DO NOT EDIT!


#ifndef IGNITION_TELEMETRY_WITH_MESSAGE_AUTONOMOUSHEARDBIT_H
#define IGNITION_TELEMETRY_WITH_MESSAGE_AUTONOMOUSHEARDBIT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ignition_telemetry_with
{
template <class ContainerAllocator>
struct AutonomousHeardBit_
{
  typedef AutonomousHeardBit_<ContainerAllocator> Type;

  AutonomousHeardBit_()
    : AutonomousManuelSelect(0)  {
    }
  AutonomousHeardBit_(const ContainerAllocator& _alloc)
    : AutonomousManuelSelect(0)  {
  (void)_alloc;
    }



   typedef uint8_t _AutonomousManuelSelect_type;
  _AutonomousManuelSelect_type AutonomousManuelSelect;





  typedef boost::shared_ptr< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> const> ConstPtr;

}; // struct AutonomousHeardBit_

typedef ::ignition_telemetry_with::AutonomousHeardBit_<std::allocator<void> > AutonomousHeardBit;

typedef boost::shared_ptr< ::ignition_telemetry_with::AutonomousHeardBit > AutonomousHeardBitPtr;
typedef boost::shared_ptr< ::ignition_telemetry_with::AutonomousHeardBit const> AutonomousHeardBitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator1> & lhs, const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator2> & rhs)
{
  return lhs.AutonomousManuelSelect == rhs.AutonomousManuelSelect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator1> & lhs, const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ignition_telemetry_with

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c39b595a65591df04cdfa147e70909cc";
  }

  static const char* value(const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc39b595a65591df0ULL;
  static const uint64_t static_value2 = 0x4cdfa147e70909ccULL;
};

template<class ContainerAllocator>
struct DataType< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ignition_telemetry_with/AutonomousHeardBit";
  }

  static const char* value(const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 AutonomousManuelSelect\n"
;
  }

  static const char* value(const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.AutonomousManuelSelect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutonomousHeardBit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ignition_telemetry_with::AutonomousHeardBit_<ContainerAllocator>& v)
  {
    s << indent << "AutonomousManuelSelect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AutonomousManuelSelect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IGNITION_TELEMETRY_WITH_MESSAGE_AUTONOMOUSHEARDBIT_H
