// Generated by gencpp from file ignition_telemetry_with/dis_messages.msg
// DO NOT EDIT!


#ifndef IGNITION_TELEMETRY_WITH_MESSAGE_DIS_MESSAGES_H
#define IGNITION_TELEMETRY_WITH_MESSAGE_DIS_MESSAGES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ignition_telemetry_with
{
template <class ContainerAllocator>
struct dis_messages_
{
  typedef dis_messages_<ContainerAllocator> Type;

  dis_messages_()
    : angle(0.0)  {
    }
  dis_messages_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> const> ConstPtr;

}; // struct dis_messages_

typedef ::ignition_telemetry_with::dis_messages_<std::allocator<void> > dis_messages;

typedef boost::shared_ptr< ::ignition_telemetry_with::dis_messages > dis_messagesPtr;
typedef boost::shared_ptr< ::ignition_telemetry_with::dis_messages const> dis_messagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ignition_telemetry_with::dis_messages_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ignition_telemetry_with::dis_messages_<ContainerAllocator1> & lhs, const ::ignition_telemetry_with::dis_messages_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ignition_telemetry_with::dis_messages_<ContainerAllocator1> & lhs, const ::ignition_telemetry_with::dis_messages_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ignition_telemetry_with

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::ignition_telemetry_with::dis_messages_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ignition_telemetry_with/dis_messages";
  }

  static const char* value(const ::ignition_telemetry_with::dis_messages_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
;
  }

  static const char* value(const ::ignition_telemetry_with::dis_messages_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dis_messages_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ignition_telemetry_with::dis_messages_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ignition_telemetry_with::dis_messages_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IGNITION_TELEMETRY_WITH_MESSAGE_DIS_MESSAGES_H
