// Generated by gencpp from file smart_can_msgs/AUTONOMOUS_SteeringMot_Control.msg
// DO NOT EDIT!


#ifndef SMART_CAN_MSGS_MESSAGE_AUTONOMOUS_STEERINGMOT_CONTROL_H
#define SMART_CAN_MSGS_MESSAGE_AUTONOMOUS_STEERINGMOT_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_can_msgs
{
template <class ContainerAllocator>
struct AUTONOMOUS_SteeringMot_Control_
{
  typedef AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> Type;

  AUTONOMOUS_SteeringMot_Control_()
    : AUTONOMOUS_SteeringMot_EN(0)
    , AUTONOMOUS_SteeringMot_PWM(0)  {
    }
  AUTONOMOUS_SteeringMot_Control_(const ContainerAllocator& _alloc)
    : AUTONOMOUS_SteeringMot_EN(0)
    , AUTONOMOUS_SteeringMot_PWM(0)  {
  (void)_alloc;
    }



   typedef uint8_t _AUTONOMOUS_SteeringMot_EN_type;
  _AUTONOMOUS_SteeringMot_EN_type AUTONOMOUS_SteeringMot_EN;

   typedef uint8_t _AUTONOMOUS_SteeringMot_PWM_type;
  _AUTONOMOUS_SteeringMot_PWM_type AUTONOMOUS_SteeringMot_PWM;





  typedef boost::shared_ptr< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> const> ConstPtr;

}; // struct AUTONOMOUS_SteeringMot_Control_

typedef ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<std::allocator<void> > AUTONOMOUS_SteeringMot_Control;

typedef boost::shared_ptr< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control > AUTONOMOUS_SteeringMot_ControlPtr;
typedef boost::shared_ptr< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control const> AUTONOMOUS_SteeringMot_ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator1> & lhs, const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator2> & rhs)
{
  return lhs.AUTONOMOUS_SteeringMot_EN == rhs.AUTONOMOUS_SteeringMot_EN &&
    lhs.AUTONOMOUS_SteeringMot_PWM == rhs.AUTONOMOUS_SteeringMot_PWM;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator1> & lhs, const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff6e7bebf0a430b5352684aa87189522";
  }

  static const char* value(const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff6e7bebf0a430b5ULL;
  static const uint64_t static_value2 = 0x352684aa87189522ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_can_msgs/AUTONOMOUS_SteeringMot_Control";
  }

  static const char* value(const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 AUTONOMOUS_SteeringMot_EN\n"
"uint8 AUTONOMOUS_SteeringMot_PWM\n"
;
  }

  static const char* value(const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.AUTONOMOUS_SteeringMot_EN);
      stream.next(m.AUTONOMOUS_SteeringMot_PWM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AUTONOMOUS_SteeringMot_Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_can_msgs::AUTONOMOUS_SteeringMot_Control_<ContainerAllocator>& v)
  {
    s << indent << "AUTONOMOUS_SteeringMot_EN: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AUTONOMOUS_SteeringMot_EN);
    s << indent << "AUTONOMOUS_SteeringMot_PWM: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AUTONOMOUS_SteeringMot_PWM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CAN_MSGS_MESSAGE_AUTONOMOUS_STEERINGMOT_CONTROL_H
