// Generated by gencpp from file smart_can_msgs/FB_MotorDriver.msg
// DO NOT EDIT!


#ifndef SMART_CAN_MSGS_MESSAGE_FB_MOTORDRIVER_H
#define SMART_CAN_MSGS_MESSAGE_FB_MOTORDRIVER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_can_msgs
{
template <class ContainerAllocator>
struct FB_MotorDriver_
{
  typedef FB_MotorDriver_<ContainerAllocator> Type;

  FB_MotorDriver_()
    : GEAR_STATUS_FROM_MOTOR(0)
    , PlusTripDistance(0)
    , VehicleRPM(0)  {
    }
  FB_MotorDriver_(const ContainerAllocator& _alloc)
    : GEAR_STATUS_FROM_MOTOR(0)
    , PlusTripDistance(0)
    , VehicleRPM(0)  {
  (void)_alloc;
    }



   typedef uint8_t _GEAR_STATUS_FROM_MOTOR_type;
  _GEAR_STATUS_FROM_MOTOR_type GEAR_STATUS_FROM_MOTOR;

   typedef uint16_t _PlusTripDistance_type;
  _PlusTripDistance_type PlusTripDistance;

   typedef uint16_t _VehicleRPM_type;
  _VehicleRPM_type VehicleRPM;





  typedef boost::shared_ptr< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> const> ConstPtr;

}; // struct FB_MotorDriver_

typedef ::smart_can_msgs::FB_MotorDriver_<std::allocator<void> > FB_MotorDriver;

typedef boost::shared_ptr< ::smart_can_msgs::FB_MotorDriver > FB_MotorDriverPtr;
typedef boost::shared_ptr< ::smart_can_msgs::FB_MotorDriver const> FB_MotorDriverConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator1> & lhs, const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator2> & rhs)
{
  return lhs.GEAR_STATUS_FROM_MOTOR == rhs.GEAR_STATUS_FROM_MOTOR &&
    lhs.PlusTripDistance == rhs.PlusTripDistance &&
    lhs.VehicleRPM == rhs.VehicleRPM;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator1> & lhs, const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee0fe8cee4053ab7ab54decef9676a69";
  }

  static const char* value(const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee0fe8cee4053ab7ULL;
  static const uint64_t static_value2 = 0xab54decef9676a69ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_can_msgs/FB_MotorDriver";
  }

  static const char* value(const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 GEAR_STATUS_FROM_MOTOR\n"
"uint16 PlusTripDistance\n"
"uint16 VehicleRPM\n"
;
  }

  static const char* value(const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.GEAR_STATUS_FROM_MOTOR);
      stream.next(m.PlusTripDistance);
      stream.next(m.VehicleRPM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FB_MotorDriver_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_can_msgs::FB_MotorDriver_<ContainerAllocator>& v)
  {
    s << indent << "GEAR_STATUS_FROM_MOTOR: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.GEAR_STATUS_FROM_MOTOR);
    s << indent << "PlusTripDistance: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.PlusTripDistance);
    s << indent << "VehicleRPM: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.VehicleRPM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CAN_MSGS_MESSAGE_FB_MOTORDRIVER_H
