// Generated by gencpp from file smart_can_msgs/snd_RCUnit_BrakeData.msg
// DO NOT EDIT!


#ifndef SMART_CAN_MSGS_MESSAGE_SND_RCUNIT_BRAKEDATA_H
#define SMART_CAN_MSGS_MESSAGE_SND_RCUNIT_BRAKEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_can_msgs
{
template <class ContainerAllocator>
struct snd_RCUnit_BrakeData_
{
  typedef snd_RCUnit_BrakeData_<ContainerAllocator> Type;

  snd_RCUnit_BrakeData_()
    : RC_BrakePedal_Speed(0)
    , RC_BrakePedal_Acc(0)
    , RC_BrakePedal_Pos(0)  {
    }
  snd_RCUnit_BrakeData_(const ContainerAllocator& _alloc)
    : RC_BrakePedal_Speed(0)
    , RC_BrakePedal_Acc(0)
    , RC_BrakePedal_Pos(0)  {
  (void)_alloc;
    }



   typedef uint16_t _RC_BrakePedal_Speed_type;
  _RC_BrakePedal_Speed_type RC_BrakePedal_Speed;

   typedef uint16_t _RC_BrakePedal_Acc_type;
  _RC_BrakePedal_Acc_type RC_BrakePedal_Acc;

   typedef uint8_t _RC_BrakePedal_Pos_type;
  _RC_BrakePedal_Pos_type RC_BrakePedal_Pos;





  typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> const> ConstPtr;

}; // struct snd_RCUnit_BrakeData_

typedef ::smart_can_msgs::snd_RCUnit_BrakeData_<std::allocator<void> > snd_RCUnit_BrakeData;

typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_BrakeData > snd_RCUnit_BrakeDataPtr;
typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_BrakeData const> snd_RCUnit_BrakeDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator1> & lhs, const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator2> & rhs)
{
  return lhs.RC_BrakePedal_Speed == rhs.RC_BrakePedal_Speed &&
    lhs.RC_BrakePedal_Acc == rhs.RC_BrakePedal_Acc &&
    lhs.RC_BrakePedal_Pos == rhs.RC_BrakePedal_Pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator1> & lhs, const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "650ea666f66da37d4464c1053ef96d40";
  }

  static const char* value(const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x650ea666f66da37dULL;
  static const uint64_t static_value2 = 0x4464c1053ef96d40ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_can_msgs/snd_RCUnit_BrakeData";
  }

  static const char* value(const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 RC_BrakePedal_Speed\n"
"uint16 RC_BrakePedal_Acc\n"
"uint8 RC_BrakePedal_Pos\n"
;
  }

  static const char* value(const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RC_BrakePedal_Speed);
      stream.next(m.RC_BrakePedal_Acc);
      stream.next(m.RC_BrakePedal_Pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct snd_RCUnit_BrakeData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_can_msgs::snd_RCUnit_BrakeData_<ContainerAllocator>& v)
  {
    s << indent << "RC_BrakePedal_Speed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RC_BrakePedal_Speed);
    s << indent << "RC_BrakePedal_Acc: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RC_BrakePedal_Acc);
    s << indent << "RC_BrakePedal_Pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RC_BrakePedal_Pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CAN_MSGS_MESSAGE_SND_RCUNIT_BRAKEDATA_H
