// Generated by gencpp from file smart_can_msgs/snd_RCUnit_SteeringData.msg
// DO NOT EDIT!


#ifndef SMART_CAN_MSGS_MESSAGE_SND_RCUNIT_STEERINGDATA_H
#define SMART_CAN_MSGS_MESSAGE_SND_RCUNIT_STEERINGDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_can_msgs
{
template <class ContainerAllocator>
struct snd_RCUnit_SteeringData_
{
  typedef snd_RCUnit_SteeringData_<ContainerAllocator> Type;

  snd_RCUnit_SteeringData_()
    : RC_Steering_RightLimit(0)
    , RC_Steering_LeftLimit(0)
    , RC_SteeringPWM(0)
    , RC_SteeringDirection(0)  {
    }
  snd_RCUnit_SteeringData_(const ContainerAllocator& _alloc)
    : RC_Steering_RightLimit(0)
    , RC_Steering_LeftLimit(0)
    , RC_SteeringPWM(0)
    , RC_SteeringDirection(0)  {
  (void)_alloc;
    }



   typedef uint8_t _RC_Steering_RightLimit_type;
  _RC_Steering_RightLimit_type RC_Steering_RightLimit;

   typedef uint8_t _RC_Steering_LeftLimit_type;
  _RC_Steering_LeftLimit_type RC_Steering_LeftLimit;

   typedef uint16_t _RC_SteeringPWM_type;
  _RC_SteeringPWM_type RC_SteeringPWM;

   typedef uint8_t _RC_SteeringDirection_type;
  _RC_SteeringDirection_type RC_SteeringDirection;





  typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> const> ConstPtr;

}; // struct snd_RCUnit_SteeringData_

typedef ::smart_can_msgs::snd_RCUnit_SteeringData_<std::allocator<void> > snd_RCUnit_SteeringData;

typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_SteeringData > snd_RCUnit_SteeringDataPtr;
typedef boost::shared_ptr< ::smart_can_msgs::snd_RCUnit_SteeringData const> snd_RCUnit_SteeringDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator1> & lhs, const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator2> & rhs)
{
  return lhs.RC_Steering_RightLimit == rhs.RC_Steering_RightLimit &&
    lhs.RC_Steering_LeftLimit == rhs.RC_Steering_LeftLimit &&
    lhs.RC_SteeringPWM == rhs.RC_SteeringPWM &&
    lhs.RC_SteeringDirection == rhs.RC_SteeringDirection;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator1> & lhs, const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbaee7c633defae17cb1a658b42efed0";
  }

  static const char* value(const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbaee7c633defae1ULL;
  static const uint64_t static_value2 = 0x7cb1a658b42efed0ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_can_msgs/snd_RCUnit_SteeringData";
  }

  static const char* value(const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 RC_Steering_RightLimit\n"
"uint8 RC_Steering_LeftLimit\n"
"uint16 RC_SteeringPWM\n"
"uint8 RC_SteeringDirection\n"
;
  }

  static const char* value(const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RC_Steering_RightLimit);
      stream.next(m.RC_Steering_LeftLimit);
      stream.next(m.RC_SteeringPWM);
      stream.next(m.RC_SteeringDirection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct snd_RCUnit_SteeringData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_can_msgs::snd_RCUnit_SteeringData_<ContainerAllocator>& v)
  {
    s << indent << "RC_Steering_RightLimit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RC_Steering_RightLimit);
    s << indent << "RC_Steering_LeftLimit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RC_Steering_LeftLimit);
    s << indent << "RC_SteeringPWM: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RC_SteeringPWM);
    s << indent << "RC_SteeringDirection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RC_SteeringDirection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CAN_MSGS_MESSAGE_SND_RCUNIT_STEERINGDATA_H
