(cl:in-package smart_can_msgs-msg)
(cl:export '(FB_VEHICLESPEED_KMH-VAL
          FB_VEHICLESPEED_KMH
          FB_REELVEHICLESPEED_KMH-VAL
          FB_REELVEHICLESPEED_KMH
          FB_REELVEHICLESPEED_MS-VAL
          FB_REELVEHICLESPEED_MS
))