(cl:in-package smart_can_msgs-msg)
(cl:export '(AUTONOMOUS_EMERGENCY-VAL
          AUTONOMOUS_EMERGENCY
          RC_WINDOWRESINTANCE-VAL
          RC_WINDOWRESINTANCE
          RC_INTERIORLIGHT-VAL
          RC_INTERIORLIGHT
          RC_REVERSELIGHT-VAL
          RC_REVERSELIGHT
          RC_DRL-VAL
          RC_DRL
          RC_BRAKELIGHT-VAL
          RC_BRAKELIGHT
          AUTONOMOUS_DOOR_OPEN-VAL
          AUTONOMOUS_DOOR_OPEN
          AUTONOMOUS_DOOR_CLOSE-VAL
          AUTONOMOUS_DOOR_CLOSE
          RC_SIGNALSTATUS-VAL
          RC_SIGNALSTATUS
          RC_LOWBEAM-VAL
          RC_LOWBEAM
          RC_HIGHBEAM-VAL
          RC_HIGHBEAM
          RC_SELECTIONGEAR-VAL
          RC_SELECTIONGEAR
          RC_IGNITION-VAL
          RC_IGNITION
))