(cl:in-package smart_can_msgs-msg)
(cl:export '(AUTONOMOUS_BRAKEMOTOR_VOLTAGE-VAL
          AUTONOMOUS_BRAKEMOTOR_VOLTAGE
          AUTONOMOUS_BRAKEPEDALMOTOR_PER-VAL
          AUTONOMOUS_BRAKEPEDALMOTOR_PER
          AUTONOMOUS_BRAKEPEDALMOTOR_ACC-VAL
          AUTONOMOUS_BRAKEPEDALMOTOR_ACC
          AUTONOMOUS_BRAKEPEDALMOTOR_EN-VAL
          AUTONOMOUS_BRAKEPEDALMOTOR_EN
))